Router.configure({
   layoutTemplate:'layout'
});

Router.route('/',function(){
   this.render('home');
});
Router.route('/accounts',function(){
   this.render('accountWrapper');
});
Router.route('/services/new',function(){
   this.render('newService');
});
Router.route('/services/list',function(){
    this.render('listServices');
});
Router.route('/appointment',function(){
   this.render('appointment')
});